#!/usr/bin/env python3
"""Blackbox oversized handshake memory modules for shell-level synthesis."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


MODULE_RE = re.compile(r"^module (\S+)")
MEMORY_RE = re.compile(r"^\s*memory(?: width (\d+))? size (\d+) (\S+)")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Input RTLIL file.")
    parser.add_argument(
        "--output-script",
        required=True,
        help="Output Yosys script that blackboxes oversized modules.",
    )
    parser.add_argument(
        "--output-report",
        required=True,
        help="Output JSON report describing externalized modules.",
    )
    parser.add_argument(
        "--min-module-bits",
        required=True,
        type=int,
        help=(
            "Externalize modules whose aggregate memory bits meet or exceed "
            "this threshold."
        ),
    )
    parser.add_argument(
        "--module-name-regex",
        default=r"^\\handshake_memory_",
        help="Only consider module names matching this regex.",
    )
    parser.add_argument(
        "--max-modules",
        type=int,
        default=None,
        help=(
            "If set, keep only the N largest matching modules after applying "
            "--min-module-bits."
        ),
    )
    return parser.parse_args()


def collect_modules(path: Path, name_re: re.Pattern[str]) -> list[dict[str, object]]:
    modules: list[dict[str, object]] = []
    current: dict[str, object] | None = None

    with path.open("r", encoding="utf-8", errors="ignore") as handle:
        for line in handle:
            module_match = MODULE_RE.match(line)
            if module_match is not None:
                name = module_match.group(1)
                current = {
                    "name": name,
                    "memories": [],
                    "total_bits": 0,
                    "matches_name_filter": bool(name_re.search(name)),
                }
                modules.append(current)
                continue

            if current is None:
                continue

            memory_match = MEMORY_RE.match(line)
            if memory_match is None:
                continue

            width = int(memory_match.group(1) or "1")
            size = int(memory_match.group(2))
            bits = width * size
            current["memories"].append(
                {
                    "name": memory_match.group(3),
                    "width": width,
                    "size": size,
                    "bits": bits,
                }
            )
            current["total_bits"] = int(current["total_bits"]) + bits

    return modules


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    output_script_path = Path(args.output_script)
    output_report_path = Path(args.output_report)
    name_re = re.compile(args.module_name_regex)

    modules = collect_modules(input_path, name_re)
    eligible = [
        module
        for module in modules
        if module["matches_name_filter"] and int(module["total_bits"]) >= args.min_module_bits
    ]
    eligible.sort(key=lambda module: (int(module["total_bits"]), str(module["name"])), reverse=True)
    selected = eligible
    if args.max_modules is not None:
        if args.max_modules < 0:
            raise SystemExit("--max-modules must be non-negative")
        selected = eligible[: args.max_modules]

    script_lines = [
        "# Auto-generated by scripts/pipeline/externalize_large_memories.py",
        "# Oversized handshake memories are blackboxed here so shell synthesis",
        "# measures controller/fabric logic while treating these modules as",
        "# external storage candidates.",
    ]
    for module in selected:
        script_lines.extend(
            [
                "select -clear",
                f"select -module {module['name']}",
                "setattr -mod -set llm2fpga_external_memory 1",
                "blackbox",
            ]
        )
    script_lines.append("select -clear")
    output_script_path.write_text("\n".join(script_lines) + "\n", encoding="utf-8")

    report = {
        "input": str(input_path),
        "eligible_module_count": len(eligible),
        "eligible_total_bits": sum(int(module["total_bits"]) for module in eligible),
        "max_modules": args.max_modules,
        "min_module_bits": args.min_module_bits,
        "module_name_regex": args.module_name_regex,
        "selected_module_count": len(selected),
        "selected_total_bits": sum(int(module["total_bits"]) for module in selected),
        "selected_modules": selected,
    }
    output_report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
