#!/usr/bin/env python3
"""Blackbox oversized handshake memory modules for shell-level synthesis."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


MODULE_RE = re.compile(r"^module (\S+)")
MEMORY_RE = re.compile(r"^\s*memory(?: width (\d+))? size (\d+) (\S+)")
def collect_selected_modules(path: Path, min_module_bits: int) -> list[dict[str, object]]:
    selected: list[dict[str, object]] = []
    current: dict[str, object] | None = None

    with path.open("r", encoding="utf-8", errors="ignore") as handle:
        for line in handle:
            module_match = MODULE_RE.match(line)
            if module_match is not None:
                if current is not None and int(current["total_bits"]) >= min_module_bits:
                    selected.append(current)
                name = module_match.group(1)
                current = (
                    {"name": name, "memories": [], "total_bits": 0}
                    if name.startswith(r"\handshake_memory_")
                    else None
                )
                continue

            if current is None:
                continue

            memory_match = MEMORY_RE.match(line)
            if memory_match is None:
                continue

            width = int(memory_match.group(1) or "1")
            size = int(memory_match.group(2))
            bits = width * size
            current["memories"].append(
                {
                    "name": memory_match.group(3),
                    "width": width,
                    "size": size,
                    "bits": bits,
                }
            )
            current["total_bits"] = int(current["total_bits"]) + bits

    if current is not None and int(current["total_bits"]) >= min_module_bits:
        selected.append(current)
    selected.sort(key=lambda module: (int(module["total_bits"]), str(module["name"])), reverse=True)
    return selected


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Input RTLIL file.")
    parser.add_argument("--output-script", required=True, help="Output Yosys script.")
    parser.add_argument("--output-report", required=True, help="Output JSON report.")
    parser.add_argument(
        "--min-module-bits",
        required=True,
        type=int,
        help="Externalize modules whose aggregate memory bits meet or exceed this threshold.",
    )
    args = parser.parse_args()
    input_path = Path(args.input)
    output_script_path = Path(args.output_script)
    output_report_path = Path(args.output_report)

    selected = collect_selected_modules(input_path, args.min_module_bits)
    selected_total_bits = sum(int(module["total_bits"]) for module in selected)

    script_lines = [
        "# Auto-generated by scripts/pipeline/externalize_large_memories.py",
        "# Oversized handshake memories are blackboxed here so shell synthesis",
        "# measures controller/fabric logic while treating these modules as",
        "# external storage candidates.",
    ]
    for module in selected:
        script_lines.extend(
            [
                "select -clear",
                f"select -module {module['name']}",
                "setattr -mod -set llm2fpga_external_memory 1",
                "blackbox",
            ]
        )
    script_lines.append("select -clear")
    output_script_path.write_text("\n".join(script_lines) + "\n", encoding="utf-8")

    report = {
        "input": str(input_path),
        "min_module_bits": args.min_module_bits,
        "selected_module_count": len(selected),
        "selected_total_bits": selected_total_bits,
        "selected_modules": selected,
    }
    output_report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
