#!/usr/bin/env bash
set -u

sha256sum survey/protocol.md survey/build/deep_review.csv survey/build/artifact_inventory.csv survey/build/repository_audit.csv
if test -d /tmp/llm2fpga-task6-r8-receipt-source/.git; then git -C /tmp/llm2fpga-task6-r8-receipt-source fetch --quiet origin e21dafa4d877c1dc7846f9e0b60c05a995d033eb; else git clone --filter=blob:none --no-checkout https://github.com/JoshuaLandgraf/cascade.git /tmp/llm2fpga-task6-r8-receipt-source; fi && git -C /tmp/llm2fpga-task6-r8-receipt-source checkout --detach e21dafa4d877c1dc7846f9e0b60c05a995d033eb && git -C /tmp/llm2fpga-task6-r8-receipt-source rev-parse HEAD && git -C /tmp/llm2fpga-task6-r8-receipt-source status --short
python3 -c "from pathlib import Path; d=Path('/tmp/llm2fpga-task6-r8-receipt-source')/'share/cascade/de10'; qsf=(d/'DE10_NANO_SoC_GHRD.qsf').read_text(); needed=['soc_system/synthesis/soc_system.qip']; referenced=[p for p in needed if p in qsf]; missing=[p for p in referenced if not (d/p).is_file()]; print('r8_qsf_references='+','.join(referenced)); print('r8_qsys_source_present='+str((d/'soc_system.qsys').is_file()).lower()); print('r8_missing_required_files='+','.join(missing)); print('r8_source_closure_complete='+str(not missing).lower())"
cmake -S /tmp/llm2fpga-task6-r8-receipt-source -B /tmp/llm2fpga-task6-r8-receipt-build -DCMAKE_BUILD_TYPE=Release && cmake --build /tmp/llm2fpga-task6-r8-receipt-build -j2
nix develop -c yosys -p 'read_verilog -I /tmp/llm2fpga-task6-r8-receipt-source /tmp/llm2fpga-task6-r8-receipt-source/share/cascade/test/benchmark/adpcm/adpcm.v; hierarchy -check -top test; proc; check'
python3 -c "from pathlib import Path; t=(Path('/tmp/llm2fpga-task6-r8-receipt-source')/'experiments/README.md').read_text().lower(); print('r8_causal_lm_interface='+str('causal' in t and 'decode' in t).lower()); print('r8_declared_workload=fpga_virtualization')"
